from roster import Roster

# ships in alphabetical order
from vehicles import (bulk_barge_B,
                      bulk_barge_C,
                      bulk_barge_D,
                      bulk_barge_E,
                      bulk_barge_F,
                      bulk_ship_C,
                      bulk_ship_D,
                      bulk_ship_E,
                      bulk_ship_F,
                      covered_hopper_carrier_F,
                      cryo_tanker_D,
                      cryo_tanker_F,
                      edibles_tanker_D,
                      edibles_tanker_F,
                      flatdeck_barge_B,
                      flatdeck_barge_D,
                      flatdeck_barge_F,
                      fruit_veg_carrier_D,
                      fruit_veg_carrier_F,
                      livestock_carrier_D,
                      livestock_carrier_F,
                      #mail_ship_E, # no very large mail ship, nonsense having so many mailbags in one vehicle
                      mail_ship_A,
                      mail_ship_B,
                      mail_ship_D,
                      pax_fast_loading_A,
                      pax_fast_loading_B,
                      pax_fast_loading_C,
                      pax_fast_loading_D,
                      pax_luxury_C,
                      pax_luxury_D,
                      piece_goods_carrier_D,
                      piece_goods_carrier_E,
                      piece_goods_carrier_F,
                      reefer_D,
                      reefer_F,
                      #supply_vessel_C,
                      #supply_vessel_D,
                      tanker_ship_B,
                      tanker_ship_C,
                      tanker_ship_D,
                      tanker_ship_E,
                      tanker_ship_F,
                      tanker_barge_D,
                      tanker_barge_E,
                      tanker_barge_F,
                      trawler_A,
                      trawler_B,
                      trawler_D,
                      universal_freighter_barge_D,
                      universal_freighter_barge_E,
                      universal_freighter_barge_F,
                      universal_freighter_ship_A,
                      universal_freighter_ship_B,
                      universal_freighter_ship_C,
                      universal_freighter_ship_D,
                      universal_freighter_ship_E,
                      universal_freighter_ship_F)


roster = Roster(id = 'default',
                numeric_id = 1,
                speeds = {'freight': {0: 25, 1950: 35},
                          'fast_freight': {}, # unused currently
                          'pax_mail': {0: 35, 1950: 45, 1980: 70}},
                # ships in buy menu order
                ships = [pax_fast_loading_A,
                         pax_fast_loading_B,
                         pax_fast_loading_C,
                         pax_fast_loading_D,
                         pax_luxury_C,
                         pax_luxury_D,
                         mail_ship_A,
                         mail_ship_B,
                         mail_ship_D,
                         universal_freighter_ship_A,
                         universal_freighter_ship_B,
                         universal_freighter_ship_C,
                         universal_freighter_ship_D,
                         universal_freighter_ship_E,
                         universal_freighter_ship_F,
                         universal_freighter_barge_D,
                         universal_freighter_barge_E,
                         universal_freighter_barge_F,
                         piece_goods_carrier_D,
                         piece_goods_carrier_E,
                         piece_goods_carrier_F,
                         #flatdeck_barge_B, # deprecate?
                         #flatdeck_barge_D, # deprecate?
                         #flatdeck_barge_F, # deprecate?
                         bulk_ship_C,
                         bulk_ship_D,
                         bulk_ship_E,
                         bulk_ship_F,
                         bulk_barge_B,
                         bulk_barge_C,
                         bulk_barge_D,
                         bulk_barge_E,
                         bulk_barge_F,
                         tanker_ship_B,
                         tanker_ship_C,
                         tanker_ship_D,
                         tanker_ship_E,
                         tanker_ship_F,
                         tanker_barge_D,
                         tanker_barge_E,
                         tanker_barge_F,
                         cryo_tanker_D,
                         cryo_tanker_F,
                         covered_hopper_carrier_F,
                         livestock_carrier_D,
                         livestock_carrier_F,
                         edibles_tanker_D,
                         edibles_tanker_F,
                         reefer_D,
                         reefer_F,
                         fruit_veg_carrier_D,
                         fruit_veg_carrier_F,
                         trawler_A,
                         trawler_B,
                         trawler_D
                         ])
