from roster import Roster

# ships in alphabetical order
from ships import (bulk_carrier_D,
                   bulk_carrier_C,
                   edibles_tanker_D,
                   edibles_tanker_C,
                   flatdeck_barge_D,
                   flatdeck_barge_C,
                   fruit_veg_carrier_D,
                   fruit_veg_carrier_C,
                   livestock_carrier_D,
                   livestock_carrier_C,
                   #mail_ship_D, # no large mail ship, nonsense having so many mailbags in one vehicle
                   mail_ship_A,
                   mail_ship_B,
                   mail_ship_C,
                   pax_fast_loading_D,
                   pax_fast_loading_A,
                   pax_fast_loading_B,
                   pax_fast_loading_C,
                   pax_luxury_D,
                   pax_luxury_C,
                   piece_goods_carrier_D,
                   piece_goods_carrier_C,
                   reefer_D,
                   reefer_C,
                   #supply_vessel_D,
                   #supply_vessel_C,
                   tanker_D,
                   tanker_C,
                   trawler_C,
                   trawler_A,
                   trawler_B,
                   universal_freighter_D,
                   universal_freighter_A,
                   universal_freighter_B,
                   universal_freighter_C)


roster = Roster(id = 'default',
                numeric_id = 1,
                express_speeds = {0: 35, 1950: 45, 1980: 70},
                freighter_speeds = {0: 25, 1950: 35},
                # ships in buy menu order
                ships = [pax_fast_loading_A,
                         pax_fast_loading_B,
                         pax_fast_loading_C,
                         pax_fast_loading_D,
                         pax_luxury_C,
                         pax_luxury_D,
                         mail_ship_A,
                         mail_ship_B,
                         mail_ship_C,
                         universal_freighter_A,
                         universal_freighter_B,
                         universal_freighter_C,
                         universal_freighter_D,
                         piece_goods_carrier_C,
                         piece_goods_carrier_D,
                         flatdeck_barge_C,
                         flatdeck_barge_D,
                         bulk_carrier_C,
                         bulk_carrier_D,
                         tanker_C,
                         tanker_D,
                         livestock_carrier_C,
                         livestock_carrier_D,
                         edibles_tanker_C,
                         edibles_tanker_D,
                         reefer_C,
                         reefer_D,
                         fruit_veg_carrier_C,
                         fruit_veg_carrier_D,
                         trawler_A,
                         trawler_B,
                         trawler_C
                         ])
